import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { WebView, WebViewMessageEvent } from 'react-native-webview';
import { useNavigation } from '@react-navigation/native';
import { FontAwesome5, Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../contexts/ThemeContext';
import { authService, faceService, getApiUrlForDisplay, imovelService, localidadeService, quarteiraoService, zonaService } from '../../services/api';

type FeatureCollection = { type: 'FeatureCollection'; features: any[] };
type LayerKey = 'municipal' | 'zonas' | 'localidades' | 'quarteiroes' | 'faces' | 'imoveis';
type Stats = { zonas: number; localidades: number; quarteiroes: number; faces: number; imoveis: number; total: number };
const EMPTY_GEO: FeatureCollection = { type: 'FeatureCollection', features: [] };
const LAYERS: { key: LayerKey; label: string; icon: string }[] = [
  { key: 'municipal', label: 'Malha municipal', icon: 'map' }, { key: 'zonas', label: 'Zonas', icon: 'draw-polygon' },
  { key: 'localidades', label: 'Localidades', icon: 'city' }, { key: 'quarteiroes', label: 'Quarteirões', icon: 'th' },
  { key: 'faces', label: 'Faces', icon: 'road' }, { key: 'imoveis', label: 'Imóveis', icon: 'home' },
];
const defaultStats: Stats = { zonas: 0, localidades: 0, quarteiroes: 0, faces: 0, imoveis: 0, total: 0 };

function safeJson(value: unknown) { return JSON.stringify(value).replace(/</g, '\\u003c'); }
function buildMapHtml(layers: Record<LayerKey, FeatureCollection>) {
  return `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#map{height:100%;width:100%;margin:0;padding:0}.title{font-weight:800;margin-bottom:5px}.sub{opacity:.75}.legend{background:rgba(22,22,22,.92);color:#ddd;padding:10px;border-radius:6px;line-height:20px;font:12px Arial}.legend b{display:block;color:#fff;margin-bottom:4px}.swatch{display:inline-block;width:20px;height:3px;margin-right:6px;vertical-align:middle}.dot{display:inline-block;width:12px;height:12px;border-radius:50%;margin:0 10px 0 4px;vertical-align:-1px}</style></head>
<body><div id="map"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const RN=window.ReactNativeWebView;
const data=${safeJson(layers)};
const map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([-8.3797,-35.4508],13);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap'}).addTo(map);
const groups={};
function post(message){try{if(RN)RN.postMessage(JSON.stringify(message));}catch(error){}}
function point(feature){const coordinates=feature.geometry&&feature.geometry.coordinates;if(feature.geometry?.type==='Point'&&Array.isArray(coordinates))return{lat:coordinates[1],lng:coordinates[0]};if(feature.geometry?.type==='Polygon'&&coordinates?.[0]?.[0])return{lat:coordinates[0][0][1],lng:coordinates[0][0][0]};return null;}
function popup(feature){const properties=feature.properties||{};return '<div class="title">'+(properties.title||properties.nome||properties.name||'Registro')+'</div><div class="sub">Tipo: '+(properties.tipo||'Outro')+'</div><div class="sub">'+(properties.subtitle||'')+'</div>';}
function createLayer(key){const collection=data[key]||{features:[]};if(key==='municipal')return L.layerGroup();return L.geoJSON(collection,{style:feature=>({color:feature.properties?.color||'#2f80ed',weight:3,fillColor:feature.properties?.color||'#2f80ed',fillOpacity:.3}),pointToLayer:(feature,latlng)=>L.circleMarker(latlng,{radius:8,fillColor:feature.properties?.color||'#2f80ed',color:'#fff',weight:2,fillOpacity:.9}),onEachFeature:(feature,item)=>{item.bindPopup(popup(feature));item.on('click',()=>{const location=point(feature);post({type:'feature_click',label:feature.properties?.title||feature.properties?.nome||feature.properties?.name||'Registro',lat:location?.lat,lng:location?.lng});});}});}
Object.keys(data).forEach(key=>{groups[key]=createLayer(key);groups[key].addTo(map);});
const legend=L.control({position:'bottomright'});legend.onAdd=()=>{const div=L.DomUtil.create('div','legend');div.innerHTML='<b>LEGENDA</b><div><span class="swatch" style="background:#606060"></span>Malha municipal</div><div><span class="swatch" style="background:#7b1fa2"></span>Zona</div><div><span class="swatch" style="background:#00897b"></span>Localidade</div><div><span class="swatch" style="background:#2f80ed"></span>Quarteirão</div><div><span class="swatch" style="background:#f39c12"></span>Face</div><div><span class="dot" style="background:#2f80ed"></span>R-Residência</div><div><span class="dot" style="background:#e67e22"></span>C-Comércio</div><div><span class="dot" style="background:#27ae60"></span>T-Terreno baldio</div><div><span class="dot" style="background:#8e44ad"></span>Outro</div>';return div;};legend.addTo(map);
window.toggleLayer=key=>{if(!groups[key])return;if(map.hasLayer(groups[key]))map.removeLayer(groups[key]);else groups[key].addTo(map);};
try{const bounds=L.featureGroup(Object.values(groups)).getBounds();if(bounds.isValid())map.fitBounds(bounds.pad(.2));}catch(error){}
post({type:'ready'});
</script></body></html>`;
}
function makePointFeature(lat: unknown, lng: unknown, properties: any) { const latitude=Number(lat); const longitude=Number(lng); if(!Number.isFinite(latitude)||!Number.isFinite(longitude)) return null; return { type:'Feature', geometry:{type:'Point',coordinates:[longitude,latitude]}, properties }; }
function groupedFeatures(rows: any[], nameKey: string, latKey: string, lngKey: string, color: string) { const groups=new Map<string,{lat:number;lng:number;count:number}>(); rows.forEach(row=>{const name=row[nameKey]||'Sem nome';const lat=Number(row[latKey]);const lng=Number(row[lngKey]);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;const old=groups.get(name)||{lat:0,lng:0,count:0};groups.set(name,{lat:old.lat+lat,lng:old.lng+lng,count:old.count+1});});return Array.from(groups,([name,value])=>makePointFeature(value.lat/value.count,value.lng/value.count,{name,title:name,subtitle:`${value.count} quarteirão(ões)`,color})).filter(Boolean); }
function groupedPolygons(mapData: FeatureCollection, groupKey: 'zona' | 'localidade', color: string) { return mapData.features.filter(feature=>feature.geometry?.type==='Polygon'||feature.geometry?.type==='MultiPolygon').map(feature=>{const name=feature.properties?.[groupKey]||'Sem nome';return {...feature,properties:{...feature.properties,title:name,subtitle:groupKey==='zona'?'Zona':'Localidade',color}}}); }

const MapaQuarteiroes: React.FC = () => {
  const navigation=useNavigation(); const { colors }=useTheme(); const webRef=useRef<WebView>(null);
  const [loading,setLoading]=useState(true); const [enabledLayers,setEnabledLayers]=useState<Record<LayerKey,boolean>>({municipal:true,zonas:true,localidades:true,quarteiroes:true,faces:true,imoveis:true}); const [selectedLabel,setSelectedLabel]=useState(''); const [stats,setStats]=useState(defaultStats);
  const [layers,setLayers]=useState<Record<LayerKey,FeatureCollection>>({municipal:EMPTY_GEO,zonas:EMPTY_GEO,localidades:EMPTY_GEO,quarteiroes:EMPTY_GEO,faces:EMPTY_GEO,imoveis:EMPTY_GEO});
  const displayedLayers=useMemo<Record<LayerKey,FeatureCollection>>(()=>({...layers,zonas:{type:'FeatureCollection',features:groupedPolygons(layers.quarteiroes,'zona','#7b1fa2')},localidades:{type:'FeatureCollection',features:groupedPolygons(layers.quarteiroes,'localidade','#00897b')}}),[layers]);
  const html=useMemo(()=>buildMapHtml(displayedLayers),[displayedLayers]);
  const load=useCallback(async()=>{setLoading(true);setSelectedLabel('');try{const apiUrl=getApiUrlForDisplay();const headers=authService.getAuthHeaders();const [statsResponse,zonas,localidades,quarteiroes,imoveis,quarteiroesMap,facesMap]=await Promise.all([fetch(`${apiUrl}/stats`,{headers}).then(response=>{if(!response.ok)throw new Error('Erro ao carregar estatísticas');return response.json()}),zonaService.list(),localidadeService.list(),quarteiraoService.list(),imovelService.list(),fetch(`${apiUrl}/quarteiroes/map`,{headers}).then(response=>{if(!response.ok)throw new Error('Erro ao carregar quarteirões');return response.json()}),faceService.getMap()]);const counts={zonas:zonas.length,localidades:localidades.length,quarteiroes:Number(statsResponse.quarteiroes||0),faces:Number(statsResponse.faces||0),imoveis:Number(statsResponse.imoveis||0)};setStats({...counts,total:Object.values(counts).reduce((sum,value)=>sum+value,0)});const imovelFeatures=imoveis.map((item:any)=>{const tipo=String(item.tipo||'Outro');const normalized=tipo.toLowerCase();const color=normalized.includes('resid')?'#2f80ed':normalized.includes('comerc')?'#e67e22':normalized.includes('terreno')||normalized.includes('baldio')?'#27ae60':'#8e44ad';return makePointFeature(item.latitude,item.longitude,{title:`${item.nome_logradouro||'Imóvel'}, ${item.numero||'S/N'}`,subtitle:'Imóvel cadastrado',tipo,color});}).filter(Boolean);setLayers({municipal:EMPTY_GEO,zonas:{type:'FeatureCollection',features:groupedFeatures(quarteiroes,'nome_zona','latitude_quadra','longitude_quadra','#8e44ad')},localidades:{type:'FeatureCollection',features:groupedFeatures(quarteiroes,'nome_localidade','latitude_quadra','longitude_quadra','#16a085')},quarteiroes:quarteiroesMap||EMPTY_GEO,faces:facesMap||EMPTY_GEO,imoveis:{type:'FeatureCollection',features:imovelFeatures}});}catch(error:any){Alert.alert('Meu mapa de campo',error?.message||'Não foi possível carregar os dados do mapa.');}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const toggleLayer=(key:LayerKey)=>{setEnabledLayers(current=>({...current,[key]:!current[key]}));webRef.current?.injectJavaScript(`toggleLayer(${JSON.stringify(key)});true;`);};
  const onMessage=useCallback((event:WebViewMessageEvent)=>{try{const message=JSON.parse(event.nativeEvent.data);if(message.type==='feature_click')setSelectedLabel(`Selecionado: ${message.label}`);if(message.type==='notice')setSelectedLabel(message.message);}catch{}},[]);
  const cards=[['Zonas',stats.zonas,'map-marker-alt','#8e44ad'],['Localidades',stats.localidades,'city','#16a085'],['Quarteirões',stats.quarteiroes,'th','#2f80ed'],['Faces',stats.faces,'road','#f39c12'],['Imóveis',stats.imoveis,'home','#d35400'],['Total geral',stats.total,'layer-group',colors.primary]] as const;
  return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]}><View style={[styles.header,{backgroundColor:colors.card,borderBottomColor:colors.border}]}><TouchableOpacity onPress={()=>navigation.goBack()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.text}/></TouchableOpacity><View style={styles.titleWrap}><Text style={[styles.title,{color:colors.text}]}>Meu mapa de campo</Text>{!!selectedLabel&&<Text style={[styles.selected,{color:colors.textSecondary}]} numberOfLines={1}>{selectedLabel}</Text>}</View><TouchableOpacity onPress={load} disabled={loading} style={styles.refresh}>{loading?<ActivityIndicator size="small" color={colors.primary}/>:<Ionicons name="refresh" size={21} color={colors.primary}/>}</TouchableOpacity></View><View style={styles.cards}>{cards.map(([label,value,icon,color])=><View key={label} style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}><FontAwesome5 name={icon} size={14} color={color}/><Text style={[styles.cardValue,{color:colors.text}]}>{value}</Text><Text style={[styles.cardLabel,{color:colors.textSecondary}]} numberOfLines={1}>{label}</Text></View>)}</View><View style={styles.controls}><Text style={[styles.controlTitle,{color:colors.text}]}>Controle do mapa</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{LAYERS.map(layer=><TouchableOpacity key={layer.key} onPress={()=>toggleLayer(layer.key)} style={[styles.filter,{borderColor:enabledLayers[layer.key]?colors.primary:colors.border,backgroundColor:enabledLayers[layer.key]?colors.primary:colors.card,opacity:enabledLayers[layer.key]?1:.65}]}><FontAwesome5 name={layer.icon} size={13} color={enabledLayers[layer.key]?'#fff':colors.text}/><Text style={{color:enabledLayers[layer.key]?'#fff':colors.text,fontWeight:'700',fontSize:12}}>{layer.label}</Text></TouchableOpacity>)}</ScrollView></View><View style={styles.mapWrap}>{loading?<View style={styles.loading}><ActivityIndicator size="large" color={colors.primary}/><Text style={{marginTop:10,color:colors.textSecondary}}>Carregando mapa...</Text></View>:<WebView ref={webRef} originWhitelist={['*']} source={{html}} javaScriptEnabled domStorageEnabled onMessage={onMessage} setSupportMultipleWindows={false}/>}</View></SafeAreaView>;
};
const styles=StyleSheet.create({safe:{flex:1},header:{minHeight:62,paddingHorizontal:12,flexDirection:'row',alignItems:'center',borderBottomWidth:1},back:{padding:8},refresh:{padding:10},titleWrap:{flex:1,marginHorizontal:8},title:{fontSize:19,fontWeight:'800'},selected:{fontSize:11,marginTop:2},cards:{flexDirection:'row',padding:8,gap:5},card:{flex:1,minHeight:78,borderRadius:8,borderWidth:1,padding:7,justifyContent:'space-between'},cardValue:{fontSize:19,fontWeight:'800'},cardLabel:{fontSize:10,fontWeight:'600'},controls:{paddingHorizontal:12,paddingBottom:10},controlTitle:{fontSize:15,fontWeight:'800',marginBottom:8},filters:{gap:8},filter:{minHeight:38,paddingHorizontal:11,borderRadius:8,borderWidth:1,flexDirection:'row',alignItems:'center',gap:7},mapWrap:{flex:1,overflow:'hidden'},loading:{flex:1,alignItems:'center',justifyContent:'center'}});
export default MapaQuarteiroes;
